name: geoml
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.11

  # -- ML stack
  - pytorch
  - torchvision
  - numpy
  - pillow
  - matplotlib
  - rasterio
  - pandas
  - geopandas
  - shapely
  - tqdm
  - requests

  # -- ONNX export
  - onnx
  - onnxruntime

  - pip
  - pip:
      - huggingface_hub
      - ultralytics      # YOLOv8 object detection
